//Header files
#include <iostream>

//If we are on APPLE
#ifdef __APPLE__
#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>
#include <OpenGL/glu.h>
//IF we are on WIN32
#elif WIN32
#include <SDL.h>
#endif

//global values go here!
SDL_Window * window;

const int WINDOW_WIDTH = 640;
const int WINDOW_HEIGHT = 480;

bool running = true;

//Global functions
void InitWindows(int width, int height, bool fullscreen)
{
	//Create a window
	window = SDL_CreateWindow(
		"Lab 1",             // window title
		SDL_WINDOWPOS_CENTERED,     // x position, centered
		SDL_WINDOWPOS_CENTERED,     // y position, centered
		width,                        // width, in pixels
		height,                        // height, in pixels
		SDL_WINDOW_OPENGL           // flags
		);
}

void CleanUp()
{
	SDL_DestroyWindow(window);
	SDL_Quit();
}

//Main Method - Entry Point
int main(int argc, char * arg[])
{
	// init everyting - SDL, if it is nonzero we have a problem
	if (SDL_Init(SDL_INIT_EVERYTHING) != 0)
	{
		std::cout << "ERROR SDL_Init " << SDL_GetError() << std::endl;

		return -1;
	}

	//Call our init function
	InitWindows(WINDOW_WIDTH, WINDOW_HEIGHT, false);

	//Game Loop
	//Value to hold the event generated by SDL
	SDL_Event event;
	//Game Loop
	while (running)
	{
		//While we still have events in the queue
		while (SDL_PollEvent(&event)) {
			//Get event type
			if (event.type == SDL_QUIT || event.type == SDL_WINDOWEVENT_CLOSE) {
				//set our boolean which controls the loop to false
				running = false;
			}
		}
	}

	//Call our cleanup
	CleanUp();
    return 0;
}